### ISSUE TITLE
Font Query

### ISSUE THREAD

**Issue by SDCITOS** [thiscouldbejd/Shiny-Shiny#5]
Hi There. 

Could you let me know what font Shiny Shiny uses by default? Is it Arial?

Our exams officer thinks that the UK exam boards require Times New Roman. Are you able to shed any light on this?

Thanks,
Oli.

**Comment by thiscouldbejd** [comment]
Hi Oli,

Apologies for the late response on this - only just picked it up now!

We don't actually specify a default font, so I think it is going to revert to the printing defaults - which is normally Roboto on Chrome OS (I believe). Haven't had any other Exams Officers mention this before though!

Are you using managed configuration? E.g. you are pushing the app out as a kiosk / managed session app to Workspace Enrolled Chrome Devices? If so - should be fairly straightforward to include a configuration option in there to allow you to specify the font that you would like for printing purposes.

Will give it a whirl and publish it to the BETA build (which is used to checking everyone is happy with new functionality before it gets merged into the live / production app) - https://chrome.google.com/webstore/detail/shiny-shiny-beta/fjikdpllkfmopbebghfjifpgcjalojjh

Will pop an update on the ticket when done! If you're not using managed config at all, let me know and we'll see what we can come up with as an alternative.

Thanks,

JD

**Comment by SDCITOS** [comment]
Hi JD,

No worries! Thanks so much for replying.

We are pushing it out to a specific exam users OU with G-Suite. We managed to get to grips with the JSON config files last week, which we hadn't played with before. We got everything working the way that our exam manager wanted, which was great.

I managed to find the JCQ exam regs file<https://www.jcq.org.uk/wp-content/uploads/2022/01/ICE_21-22_FINAL.pdf> on google which doesn't make any specific reference to font type, so I think you're right - it probably doesn't matter as long as it's a legible font. However, it would be excellent to have the ability to change it.

We are currently using the BETA app. Will we need to remove and re-add it into G-Suite to reflect the changes once they've been made?

Many thanks,
Oli.




Mr O Sparrow
IT Services Technician
________________________________
St Dunstan's College
Stanstead Road
London
SE6 4TY

020 8516 7200 | Contact<https://www.stdunstans.org.uk/contact/contact-us> | About<https://www.stdunstans.org.uk/about/headmasters-welcome>
Home<https://www.stdunstans.org.uk/> | Facebook<https://www.facebook.com/StDunstansColl> | Twitter<https://twitter.com/StDunstansColl>
        [https://www.stdunstans.org.uk/uploaded/themes/default_18/images/shield_3580e3b3-bac4-42b3-a2c7-9fd50a0ef1ad.png]

A registered charity number 312747
________________________________
[https://resources.finalsite.net/images/f_auto,q_auto,t_image_size_4/v1602514447/stdunstansorguk/dw7vrpl4rlim48wq8z4b/EmailfooterFebruary2020_1.jpg]<https://www.stdunstans.org.uk/about/our-awards-and-reports>
________________________________
'An ambitious, forward-thinking community that inspires and supports individuals to thrive'

CONFIDENTIALITY NOTICE
This communication is from St Dunstan's Educational Foundation, Stanstead Road, London SE6 4TY.
The information contained in this communication is confidential and may be privileged. It is for the exclusive use of the intended recipient.
If you are not the intended recipient, please do not distribute, copy or otherwise use this communication or the information in it.
If you have received this communication in error, please notify us by e-mail at ***@***.******@***.***> and then delete the e-mail
(including any attachments) and any copies of it.

**Comment by thiscouldbejd** [comment]
Hi Oli,

Great. Glad it is working well for you!

I have added a feature to the BETA release (current version 0.8.6). This is currently just available via the JSON configuration, and the key is:

"PRINT_FONT_FAMILY": {"Value" : "'Tinos', serif"},

(remember the comma shouldn't be there for the final setting in the JSON)

As Chrome Web Apps can't download or reference files on the Internet, Shiny is just using what is known in web development as the default font stack (e.g. whatever fonts are available on the device). You can check the fonts available on Chrome OS systems by typing: **chrome://settings/fonts** into the browser.

The format of the value is the same as the CSS font-family property (except without the trailing semi-colon). More details are here: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

There are quite a few serif style fonts available on Chrome OS. I believe Tinos is normally the default, so if you just specify 'serif' as your choice, it should default to that.

If there is a very particular font you need, am not adverse to including the font file within the packaged app if it is open source and available on Google Fonts (https://fonts.google.com/). But I suspect there are probably enough build in to satisfy most needs.

Your devices should update automatically to the most current version. You can also force an update on a device by visiting the extensions page (chrome://extensions/) and hitting update. You can check the versions on here too. For devices you have locked into kiosk mode - go to the generic help page on Shiny and scroll to the bottom - it will tell you the version number.

Hope that makes sense - let me know if it does what you want, or if you have any suggestions / issues.

Yours,

JD

**Comment by SDCITOS** [comment]
Hi JD,

That's worked brilliantly - thank you! Thanks again for the app, it's exactly what we needed.

Do you know whether Shiny!Shiny! will stay active until 2025 (or whenever Google finally decide to pull Chrome apps)? We are an enterprise education customer and we are using Chromebooks.

Many thanks,
Oli.



Mr O Sparrow
IT Services Technician
________________________________
St Dunstan's College
Stanstead Road
London
SE6 4TY

020 8516 7200 | Contact<https://www.stdunstans.org.uk/contact/contact-us> | About<https://www.stdunstans.org.uk/about/headmasters-welcome>
Home<https://www.stdunstans.org.uk/> | Facebook<https://www.facebook.com/StDunstansColl> | Twitter<https://twitter.com/StDunstansColl>
        [https://www.stdunstans.org.uk/uploaded/themes/default_18/images/shield_3580e3b3-bac4-42b3-a2c7-9fd50a0ef1ad.png]

A registered charity number 312747
________________________________
[https://resources.finalsite.net/images/f_auto,q_auto,t_image_size_4/v1602514447/stdunstansorguk/dw7vrpl4rlim48wq8z4b/EmailfooterFebruary2020_1.jpg]<https://www.stdunstans.org.uk/about/our-awards-and-reports>
________________________________
'An ambitious, forward-thinking community that inspires and supports individuals to thrive'

CONFIDENTIALITY NOTICE
This communication is from St Dunstan's Educational Foundation, Stanstead Road, London SE6 4TY.
The information contained in this communication is confidential and may be privileged. It is for the exclusive use of the intended recipient.
If you are not the intended recipient, please do not distribute, copy or otherwise use this communication or the information in it.
If you have received this communication in error, please notify us by e-mail at ***@***.******@***.***> and then delete the e-mail
(including any attachments) and any copies of it.

**Comment by thiscouldbejd** [comment]
Hi Oli,

Excellent! Glad it is working :)

So - the position with (packaged) Chrome Apps is a bit unclear. There is this deadline of this summer but I think that is just for updating certain types of apps - and support being officially dropped. But the app should stay active for as long as Google carry on letting people use them! I am also currently working on a PWA (progressive web app) version....which is basically the same app, but hosted on it's own website. This is all going fine so far, and the JSON configuration works fine with PWAs (although it isn't brilliantly documented by Google as it is a relatively new API / feature). I hope to have the PWA feature complete for schools to test shortly - but even though you will be able to deploy via Google Admin it won't interfere with the existing version (e.g. they should co-exist happily).

So - I don't currently see any reason you won't have a working version of the app for many years to come.

Yours,

JD.

**Comment by SDCITOS** [comment]
Awesome! Thanks JD. You've saved us a lot of time and moneys. Thanks for all your hard work.

All the best,
Oli.



Mr O Sparrow
IT Services Technician
________________________________
St Dunstan's College
Stanstead Road
London
SE6 4TY

020 8516 7200 | Contact<https://www.stdunstans.org.uk/contact/contact-us> | About<https://www.stdunstans.org.uk/about/headmasters-welcome>
Home<https://www.stdunstans.org.uk/> | Facebook<https://www.facebook.com/StDunstansColl> | Twitter<https://twitter.com/StDunstansColl>
        [https://www.stdunstans.org.uk/uploaded/themes/default_18/images/shield_3580e3b3-bac4-42b3-a2c7-9fd50a0ef1ad.png]

A registered charity number 312747
________________________________
[https://resources.finalsite.net/images/f_auto,q_auto,t_image_size_4/v1602514447/stdunstansorguk/dw7vrpl4rlim48wq8z4b/EmailfooterFebruary2020_1.jpg]<https://www.stdunstans.org.uk/about/our-awards-and-reports>
________________________________
'An ambitious, forward-thinking community that inspires and supports individuals to thrive'

CONFIDENTIALITY NOTICE
This communication is from St Dunstan's Educational Foundation, Stanstead Road, London SE6 4TY.
The information contained in this communication is confidential and may be privileged. It is for the exclusive use of the intended recipient.
If you are not the intended recipient, please do not distribute, copy or otherwise use this communication or the information in it.
If you have received this communication in error, please notify us by e-mail at ***@***.******@***.***> and then delete the e-mail
(including any attachments) and any copies of it.
